[log]
level = NOTICE

[video]
width = 1920
height = 1080
fps = 30
;[CRF | ABR]
method = CRF      
;if ABR bitrate is efficient
bitrate = 1440    
;if CRF rf_constant is efficient [0 - 51] degree of loss; default is 23; rf_constant < 10  frame size is bigger than live555 max frame size);
rf_constant = 23  
;IDR-frames 
min_ikeyint = 30
max_ikeyiny = 60
;[YUY2 | MJPEG]
format = MJPEG
device = /dev/video0

[Server]
port = 8000